spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:GbTD8SgMCDRSFsp34KiFe-8wAJaYDiStBSUFCnKlbhiwnN_2@f9960818-f8e5-4f32-9478-a65953c876a0.asia-south1.firestore.goog:443/dp-capstone-new?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}