spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:tKjKWXEEZWnOZZpDoUbaUk0_RV7gVU7MnqztoYjP26XIW9ZR@3149a823-2bb4-4291-884e-46308fd826dc.asia-south1.firestore.goog:443/db-capstone1?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}