spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:1DLa-OLopxzOUydHawa9htZQnPoAue1FKZcASvFKqXeE7eju@04f2a5c9-24a1-4498-931c-c28e59a5c26f.asia-south1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}